trufnetwork/node

deployments/Dockerfile

- fixed the postgresql-client to version 16
resolves: https://github.com/trufnetwork/node/issues/768
Tested locally with `task compode-dev` it is now works

fix: able to run latest node version

---

deployments/Dockerfile

- fix #796 
already deployed to production

chore: update docker image to support v0.9.4

---

internal/contracts/contracts_behaviors.md

chore: define stream behavior contracts and expectations

---

Taskfile.yml
compose.yaml
deployments/Dockerfile
deployments/dev-net/devnet-compose.yaml
deployments/tsn-entrypoint.sh

This pull request includes several changes to the Docker and configuration files to simplify the setup process and remove unnecessary services. The most important changes involve the removal of the `tsn-conf` service, updates to the Dockerfile to streamline the build process, and modifications to the entrypoint script to include a configuration script.
* Removed the `tsn-conf` service from `compose.yaml` and `devnet-compose.yaml`, along with associated volumes and dependencies. [[1]](diffhunk://#diff-facaded51b7d1c9656ae43b449b69aa398fee9129321a0001d97048c00c8cc1cL28-L52) [[2]](diffhunk://#diff-facaded51b7d1c9656ae43b449b69aa398fee9129321a0001d97048c00c8cc1cL91-L92) [[3]](diffhunk://#diff-9f29cd8cb8386d99930c78ebc919dfe309503c934a1b8560b147af3323323af6L56-L82) …

chore(2.0): initialize node with setup on compose

---

internal/contracts/contracts_behaviors.md
internal/contracts/tests/common_test.go
internal/contracts/tests/primitive_test.go

This pull request includes various changes to the `internal/contracts` directory to improve the clarity and organization of test cases and documentation. The most important changes are the renaming of test functions to include specific identifiers and the addition of encoded references in the documentation.
* [`internal/contracts/tests/common_test.go`](diffhunk://#diff-3f1030d5993be684e0b4e1fa6e098ca1aeb18650956c580a58f72b447b1a2878L39-R39): Renamed `TestMetadataInsertionAndRetrieval` to `TestCOMMON04MetadataInsertionAndRetrieval` to provide a more descriptive name.
* [`internal/contracts/tests/primitive_test.go`](diffhunk://#diff-f586f4d766fb1c5f6d5a8d0b3d9828023b61a82884c07a2160749c1abfb3db74R31-R35): Renamed several test functions to include specific identifiers such as …

test: Querying behaviors

---

deployments/infra/go.mod
deployments/infra/go.sum
internal/migrations/000-initial-data.sql
internal/migrations/001-common-actions.sql
internal/migrations/002-primitive-insertion.sql
tests/streams/other/other_test.go
tests/streams/primitive_test.go
tests/streams/utils/utils.go

This pull request introduces a new migration script to handle primitive actions related to the events stream. The script includes actions for inserting records, checking if the contract is initiated, retrieving metadata, and verifying wallet permissions. The most important changes are:
* [`internal/migrations/002-primitive-insertion.sql`](diffhunk://#diff-8e63b9b0208496d0b6cb225c75731da2507ffd8b94cda3c8f9a1f66591b9ac6eR1-R116): Added a migration script that defines actions for inserting records into the `primitive_events` table, checking if the contract/stream is initiated, retrieving metadata with pagination, and verifying if a wallet is allowed to write.
resolves: https://github.com/trufnetwork/node/issues/821
I am able to create the actions, but unable to test
Blocked by:
- …

chore: data insertion implementation

---

internal/migrations/001-common-actions.sql
tests/streams/auth/auth_test.go

This pull request introduces a new action for transferring stream ownership and re-enables tests for stream ownership transfer. The main changes include the addition of the `transfer_stream_ownership` action in the SQL script and the reimplementation of the related tests in the Go test file.
New action for stream ownership transfer:
* [`internal/migrations/001-common-actions.sql`](diffhunk://#diff-04a50fe53ce6b9fee5c3cc552e841ac811e6fc3de3777dec6885aa73d2193f29R420-R440): Added `transfer_stream_ownership` action to allow stream owners to transfer ownership to a new Ethereum address, including validation for the new owner's address.
Re-enabled and updated tests for stream ownership transfer:
* [`tests/streams/auth/auth_test.go`](diffhunk://#diff-7ffa2f7a31ff6873592c58368ff2e987abd9a893e9527 …

feat: owner transfer

---

internal/migrations/001-common-actions.sql
tests/streams/auth/auth_test.go
tests/streams/other/other_test.go

This pull request includes changes to improve the validation of Ethereum addresses and to enhance the corresponding test cases. The most important changes include the introduction of a new function to validate Ethereum addresses and updates to the test cases to ensure proper validation.
Improvements to Ethereum address validation:
* [`internal/migrations/001-common-actions.sql`](diffhunk://#diff-04a50fe53ce6b9fee5c3cc552e841ac811e6fc3de3777dec6885aa73d2193f29L15-R15): Introduced the `check_ethereum_address` function to validate Ethereum addresses by checking their length, prefix, and character composition. This function is now used in multiple actions to ensure address validity. [[1]](diffhunk://#diff-04a50fe53ce6b9fee5c3cc552e841ac811e6fc3de3777dec6885aa73d2193f29L15-R15) …

chore: verify Ethereum address on stream creation and transfer

---

Taskfile.yml
scripts/migrate.sh

Adding utility task so SQL execution on main namespace can be easily triggered
This pull request adds a new task for running SQL migrations and includes a corresponding script to execute the migrations.
New task addition:
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eR162-R166): Added a new task `action-migrate` to run the migration action for all SQL files.
New script for migrations:
* [`scripts/migrate.sh`](diffhunk://#diff-47309020f41e430ed808f60c7bcff6b38acffd93682044ffd28cf26f2d7fa79eR1-R5): Added a script to get all `.sql` files in the `./internal/migrations` folder and run them using `kwil-cli exec-sql`.

chore: easier pre-defined functions deployment

---

internal/migrations/000-initial-data.sql
internal/migrations/009-truflation-query.sql

added ability to insert and fetch truflation created_at
resolves: https://github.com/trufnetwork/node/issues/899

feat: insert truflation's created at into TN

---

internal/migrations/003-primitive-insertion.sql

resolves: https://github.com/trufnetwork/node/issues/904
~I can't get it work with recursive function. I revert it with the looped version.
Although might be slower, but the slow speed is not noticeable~

fix: insert records in batches on multiple streams

---

deployments/infra/lib/constructs/validator_set/node.go
deployments/infra/lib/kwil-network/generate_genesis.go
deployments/infra/lib/kwil-network/generate_node_keys.go
deployments/infra/lib/kwil-network/generate_node_keys_integration_test.go
deployments/infra/lib/kwil-network/network_config_gen.go
deployments/infra/lib/observer/attach.go

- resolves #897 
already deployed to prod

feat: production deploy compatible stacks

---

internal/migrations/010-get-latest-write-activity.sql

resolves: https://github.com/trufnetwork/node/issues/910
Tested locally

feat: view the latest write activity

---

README.md
Taskfile.yml
deployments/indexer/dev-indexer-compose.yaml
scripts/migrate.sh

- general maintainability updates to our taskfile, and adapting to new configurations necessary
- fix #896 
ran some commands here, but the made the structure easier to adapt if needed

feat: enhance Taskfile for improved development

---

internal/migrations/001-common-actions.sql
internal/migrations/002-authorization.sql
internal/migrations/003-primitive-insertion.sql
internal/migrations/004-composed-taxonomy.sql
internal/migrations/005-primitive-query.sql
internal/migrations/006-composed-query.sql
internal/migrations/007-composed-query-derivate.sql
internal/migrations/008-public-query.sql
internal/migrations/009-truflation-query.sql
internal/migrations/010-get-latest-write-activity.sql

resolves: https://github.com/trufnetwork/node/issues/916

chore: make all wallet format case-insensitive by lowercase

---

Taskfile.yml
internal/migrations/001-common-actions.sql
scripts/migrate.sh

- returns the result from streams calculation
- faster migration for dev purposes by waiting only for the last apply
- fix #925

chore: return existing streams & faster migrate

---

Taskfile.yml
internal/migrations/003-primitive-insertion.sql
tests/streams/query/query_test.go

resolves: https://github.com/trufnetwork/node/issues/937
Passed all the tests.

chore: data insertion efficiency by skipping zero values

---

README.md

chore: change indexer url

---

internal/migrations/001-common-actions.sql
tests/streams/auth/auth_test.go

applies known improvement to efficiently filter streams
fix #949 
It's already applied. prior to this change, filtering 1000 streams took 40 seconds, now it's 1 second

feat: enhance filter_streams_by_existence action

---

deployments/infra/config/node/kwild-config.tmpl
deployments/infra/lib/observer/assets.go
deployments/infra/lib/observer/attach.go
deployments/infra/lib/observer/initialization_scripts.go
deployments/infra/lib/observer/start_observer.go
deployments/infra/scripts/renderer/render_test.go
deployments/infra/scripts/renderer/templates/observer_start.sh.tmpl
deployments/infra/scripts/renderer/testdata/TestObserverScript_RenderMatchesGolden.golden
deployments/infra/scripts/renderer/testdata/observer_start_before.golden
deployments/infra/scripts/renderer/types.go

- fix region variable on script
- add recent parameters from node
- fix assets path
- fix #956 
already deployed

chore: add observer service to CDK deployment

---

internal/migrations/001-common-actions.sql
tests/streams/query/query_test.go
tests/streams/utils/procedure/execute.go

resolves: https://github.com/trufnetwork/truf-network/issues/828
- Local test passed
- Migrated

chore: block height filter on list streams

---

internal/migrations/013-role-actions.sql

- fix #985 
- ran some tests to ensure still compiles

chore: update role assertion actions to be private view

---

go.mod
go.sum

bump kwil
- includes https://github.com/trufnetwork/kwil-db/pull/1525

chore: bump kwil

---

internal/migrations/009-truflation-query.sql
tests/streams/truflation_composed_frozen_test.go

resolves: https://github.com/trufnetwork/node/issues/1009

feat: truflation frozen mechanism on composed streams records

---

extensions/tn_cache/internal/db_ops.go
extensions/tn_cache/internal/db_ops_test.go
extensions/tn_cache/tn_cache.go
extensions/tn_cache/tn_cache_test.go

resolves: https://github.com/trufnetwork/node/issues/1020
Unit test passed

chore: cache storage schema for TN Cache

---

extensions/tn_cache/tn_cache.go
extensions/tn_cache/tn_cache_test.go

resolves: https://github.com/trufnetwork/node/issues/1024
Unit test successfull

chore: register TN Cache SQL Functions

---

internal/migrations/000-initial-data.sql

resolves: https://github.com/trufnetwork/node/issues/1039
local node migration
if approved, will migrate on `tn-v2`

chore: add data providers table

---

internal/migrations/017-normalize-tables.sql

resolves: https://github.com/trufnetwork/node/issues/1041
locally tested

chore: normalize metadata table

---

internal/migrations/017-normalize-tables.sql

resolves: https://github.com/trufnetwork/node/issues/1042
local migration

chore: normalize taxonomies table

---

internal/migrations/017-normalize-tables.sql

resolves: https://github.com/trufnetwork/node/issues/1043
local migration

chore: normalize primitive events table

---

internal/migrations/001-common-actions.sql
internal/migrations/003-primitive-insertion.sql
internal/migrations/009-truflation-query.sql

resolves: https://github.com/trufnetwork/node/issues/1063
Batch Insertion on `query_test` file

chore: optimize stream ids lookup

---

internal/migrations/008-public-query.sql
internal/migrations/010-get-latest-write-activity.sql
internal/migrations/011-get-database-size.sql
tests/streams/database_size_test.go

resolves: https://github.com/trufnetwork/node/issues/1077
tests passed

chore: adjust utilities actions to normalized tables

---

internal/migrations/009-truflation-query.sql

resolves: https://github.com/trufnetwork/node/issues/1079
note: the calculation of indexes are not updated because we decided not to use it after previous Goal and issues.
tests passed

chore: update truflation query

---

docs/node-upgrade-guide.md

resolves: https://github.com/trufnetwork/truf-network/issues/1053

docs: view notes about binary built location
